app = "n8n-fly-app"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"
  NODE_ENV = "production"
  WEBHOOK_URL = "https://n8n-fly-app.fly.dev/"
  GENERIC_TIMEZONE = "Asia/Ho_Chi_Minh"

[[mounts]]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1024"
  cpu_kind = "shared"
  cpus = 1
